mod 'module_data',  '0.0.1', :github_tarball => 'ripienaar/puppet-module-data'
mod 'boxen',        '3.6.1', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib',       '4.1.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
